"""
Export Module - Export content to multiple formats
Supports JSON, TXT, and formatted educational documents
"""

import json
from datetime import datetime
from typing import Dict

class ContentExporter:
    
    @staticmethod
    def to_json(content: Dict, metadata: Dict = None) -> str:
        """Export to JSON format"""
        export_data = {
            "metadata": metadata or {
                "exported_at": datetime.now().isoformat(),
                "format": "json",
                "version": "1.0"
            },
            "content": content
        }
        return json.dumps(export_data, indent=2)
    
    @staticmethod
    def to_text(content: Dict, grade: int, topic: str) -> str:
        """Export to formatted text document"""
        lines = []
        lines.append("=" * 70)
        lines.append(f"EDUCATIONAL CONTENT - GRADE {grade}")
        lines.append(f"Topic: {topic}")
        lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("=" * 70)
        lines.append("")
        
        # Explanation section
        lines.append("EXPLANATION:")
        lines.append("-" * 70)
        lines.append(content.get('explanation', 'No explanation provided'))
        lines.append("")
        
        # MCQs section
        lines.append("MULTIPLE CHOICE QUESTIONS:")
        lines.append("-" * 70)
        
        mcqs = content.get('mcqs', [])
        for i, mcq in enumerate(mcqs, 1):
            lines.append(f"\nQuestion {i}:")
            lines.append(f"  {mcq.get('question', '')}")
            lines.append("")
            
            for option in mcq.get('options', []):
                lines.append(f"  {option}")
            
            lines.append("")
            lines.append(f"  ✓ Correct Answer: {mcq.get('answer', 'N/A')}")
            lines.append("")
        
        lines.append("=" * 70)
        lines.append("End of Document")
        lines.append("=" * 70)
        
        return "\n".join(lines)
    
    @staticmethod
    def to_markdown(content: Dict, grade: int, topic: str, review: Dict = None) -> str:
        """Export to Markdown format"""
        lines = []
        lines.append(f"# Educational Content - Grade {grade}")
        lines.append(f"**Topic:** {topic}")
        lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("")
        
        # Explanation
        lines.append("## 📖 Explanation")
        lines.append("")
        lines.append(content.get('explanation', 'No explanation provided'))
        lines.append("")
        
        # MCQs
        lines.append("## ❓ Multiple Choice Questions")
        lines.append("")
        
        mcqs = content.get('mcqs', [])
        for i, mcq in enumerate(mcqs, 1):
            lines.append(f"### Question {i}")
            lines.append(f"{mcq.get('question', '')}")
            lines.append("")
            
            for option in mcq.get('options', []):
                lines.append(f"- {option}")
            
            lines.append("")
            lines.append(f"**✓ Answer:** {mcq.get('answer', 'N/A')}")
            lines.append("")
        
        # Review section if available
        if review:
            lines.append("## 🔍 Quality Review")
            lines.append("")
            status = review.get('status', 'unknown')
            status_emoji = "✅" if status == "pass" else "❌"
            lines.append(f"**Status:** {status_emoji} {status.upper()}")
            lines.append("")
            
            feedback = review.get('feedback', [])
            if feedback:
                lines.append("**Feedback:**")
                for item in feedback:
                    lines.append(f"- {item}")
                lines.append("")
        
        lines.append("---")
        lines.append("*Generated by Educational Content Generator*")
        
        return "\n".join(lines)
    
    @staticmethod
    def to_study_guide(content: Dict, grade: int, topic: str) -> str:
        """Export as a study guide format"""
        lines = []
        lines.append("╔" + "═" * 68 + "╗")
        lines.append(f"║{' ' * 20}STUDY GUIDE - GRADE {grade}{' ' * (48 - len(str(grade)))}║")
        lines.append("╚" + "═" * 68 + "╝")
        lines.append("")
        lines.append(f"📚 Topic: {topic}")
        lines.append(f"📅 Date: {datetime.now().strftime('%B %d, %Y')}")
        lines.append("")
        lines.append("─" * 70)
        lines.append("")
        
        # Key Concepts
        lines.append("🎯 KEY CONCEPTS:")
        lines.append("")
        lines.append(content.get('explanation', 'No explanation provided'))
        lines.append("")
        lines.append("─" * 70)
        lines.append("")
        
        # Practice Questions
        lines.append("✏️  PRACTICE QUESTIONS:")
        lines.append("")
        
        mcqs = content.get('mcqs', [])
        for i, mcq in enumerate(mcqs, 1):
            lines.append(f"[Q{i}] {mcq.get('question', '')}")
            lines.append("")
            
            for option in mcq.get('options', []):
                lines.append(f"    {option}")
            lines.append("")
        
        # Answer Key
        lines.append("─" * 70)
        lines.append("")
        lines.append("🔑 ANSWER KEY:")
        lines.append("")
        
        for i, mcq in enumerate(mcqs, 1):
            lines.append(f"Question {i}: {mcq.get('answer', 'N/A')}")
        
        lines.append("")
        lines.append("─" * 70)
        lines.append("💡 Study Tips:")
        lines.append("• Review the key concepts carefully")
        lines.append("• Try answering questions without looking at options")
        lines.append("• Understand why each answer is correct")
        lines.append("• Practice explaining concepts in your own words")
        lines.append("")
        
        return "\n".join(lines)
    
    @staticmethod
    def to_teacher_version(content: Dict, grade: int, topic: str, review: Dict = None) -> str:
        """Export with teacher notes and review details"""
        lines = []
        lines.append("┌" + "─" * 68 + "┐")
        lines.append(f"│  TEACHER'S VERSION - Grade {grade}: {topic}{' ' * (68 - len(topic) - len(str(grade)) - 27)}│")
        lines.append("└" + "─" * 68 + "┘")
        lines.append("")
        
        # Teaching notes
        lines.append("📋 TEACHING NOTES:")
        lines.append("")
        lines.append(f"Target Grade: {grade}")
        lines.append(f"Topic: {topic}")
        lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        
        if review:
            status = review.get('status', 'unknown')
            lines.append(f"Quality Status: {'✅ Passed' if status == 'pass' else '⚠️ Needs Review'}")
        
        lines.append("")
        lines.append("─" * 70)
        lines.append("")
        
        # Content
        lines.append("📖 EXPLANATION (for students):")
        lines.append("")
        lines.append(content.get('explanation', ''))
        lines.append("")
        
        # Questions with detailed answers
        lines.append("─" * 70)
        lines.append("")
        lines.append("❓ ASSESSMENT QUESTIONS:")
        lines.append("")
        
        mcqs = content.get('mcqs', [])
        for i, mcq in enumerate(mcqs, 1):
            lines.append(f"Question {i}:")
            lines.append(f"  {mcq.get('question', '')}")
            lines.append("")
            lines.append("  Options:")
            
            answer = mcq.get('answer', '')
            for option in mcq.get('options', []):
                marker = "  ✓" if option.startswith(answer) else "  ○"
                lines.append(f"  {marker} {option}")
            
            lines.append("")
            lines.append(f"  📌 Correct Answer: {answer}")
            lines.append("")
        
        # Review feedback if available
        if review and review.get('feedback'):
            lines.append("─" * 70)
            lines.append("")
            lines.append("🔍 QUALITY REVIEW NOTES:")
            lines.append("")
            for item in review.get('feedback', []):
                lines.append(f"  • {item}")
            lines.append("")
        
        lines.append("─" * 70)
        lines.append("Generated by Educational Content Generator AI System")
        
        return "\n".join(lines)
